// Auto-generated Urdu translations for Learn Hub content. Do not edit by hand.
export const LEARN_UR: Record<string, string> = {
  "What is a Candlestick?": "کینڈل سٹک کیا ہے؟",
  "The building block of every PSX price chart": "ہر PSX پرائس چارٹ کا بنیادی جزو",
  "PSX Basics": "PSX کی بنیادی باتیں",
  "What's a Doji candle?": "ڈوجی کینڈل کیا ہے؟",
  "Show me a bullish pattern": "مجھے ایک بلش پیٹرن دکھائیں",
  "How do I use this on PSX?": "میں اسے PSX پر کیسے استعمال کروں؟",
  "Introduction": "تعارف",
  "Before you can read any PSX chart, you need to understand the building block of all price charts: the candlestick. Every candle tells you the story of a stock during a specific time period — whether buyers or sellers were in control.": "کسی بھی PSX چارٹ کو پڑھنے سے پہلے، آپ کو تمام پرائس چارٹس کے بنیادی جزو کو سمجھنے کی ضرورت ہے: کینڈل سٹک۔ ہر کینڈل آپ کو ایک مخصوص وقت کے دوران اسٹاک کی کہانی بتاتی ہے — چاہے خریدار کنٹرول میں تھے یا بیچنے والے۔",
  "Each candle on a 1-day chart represents one full trading day on PSX (9:30 AM to 3:30 PM). On a 1-hour chart, each candle = 1 hour of trading.": "1 دن کے چارٹ پر ہر کینڈل PSX پر ایک مکمل تجارتی دن (9:30 AM سے 3:30 PM) کی نمائندگی کرتی ہے۔ 1 گھنٹے کے چارٹ پر، ہر کینڈل = 1 گھنٹہ کی ٹریڈنگ۔",
  "Anatomy of a Candlestick": "کینڈل سٹک کی ساخت",
  "Every candlestick has four data points, known as OHLC:": "ہر کینڈل سٹک کے چار ڈیٹا پوائنٹس ہوتے ہیں، جنہیں OHLC کہا جاتا ہے:",
  "O — Open:   Price at market open": "O — اوپن: مارکیٹ کھلنے پر قیمت",
  "H — High:   Highest price reached": "H — ہائی: سب سے زیادہ قیمت تک پہنچی",
  "L — Low:    Lowest price reached": "L — لو: سب سے کم قیمت تک پہنچی",
  "C — Close:  Price at market close": "C — کلوز: مارکیٹ بند ہونے پر قیمت",
  "The thick part of the candle is called the BODY. It stretches from the Open to the Close price. The thin lines above and below the body are called WICKS (or shadows) — they show how far price traveled beyond the open/close range.": "کینڈل کا موٹا حصہ باڈی کہلاتا ہے۔ یہ اوپن سے کلوز قیمت تک پھیلا ہوتا ہے۔ باڈی کے اوپر اور نیچے کی پتلی لکیریں وکس (یا شیڈوز) کہلاتی ہیں — یہ دکھاتی ہیں کہ قیمت اوپن/کلوز رینج سے کتنی دور گئی۔",
  "Bullish vs Bearish Candles": "بلش بمقابلہ بیئرش کینڈلز",
  "The color of a candle tells you instantly who won the battle between buyers and sellers that period:": "ایک کینڈل کا رنگ آپ کو فوری طور پر بتاتا ہے کہ اس مدت میں خریداروں اور بیچنے والوں کے درمیان جنگ کون جیتا:",
  "Type": "قسم",
  "Color": "رنگ",
  "Meaning": "مطلب",
  "Close vs Open": "کلوز بمقابلہ اوپن",
  "Bullish": "بلش",
  "Teal/Green": "ٹیل/سبز",
  "Buyers in control": "خریدار کنٹرول میں",
  "Close > Open": "بند > کھلا",
  "Bearish": "منفی",
  "Red": "سرخ",
  "Sellers in control": "بیچنے والے حاوی",
  "Close < Open": "بند < کھلا",
  "Doji": "ڈوجی",
  "Gray": "سرمئی",
  "Indecision, no clear winner": "غیر فیصلہ کن، کوئی واضح فاتح نہیں",
  "Close ≈ Open": "بند ≈ کھلا",
  "HBL on June 5, 2026: Open: PKR 139.20 | High: PKR 143.80 | Low: PKR 138.50 | Close: 142.50. Result: GREEN candle. Body = 139.20 to 142.50. Upper wick = 142.50 to 143.80. Lower wick = 139.20 to 138.50. HBL had a bullish day.": "HBL 5 جون 2026 کو: کھلا: PKR 139.20 | زیادہ: PKR 143.80 | کم: PKR 138.50 | بند: 142.50۔ نتیجہ: سبز کینڈل۔ باڈی = 139.20 سے 142.50۔ اوپری وِک = 142.50 سے 143.80۔ نچلی وِک = 139.20 سے 138.50۔ HBL کا دن تیزی کا رہا۔",
  "What the Wicks Tell You": "وِکس آپ کو کیا بتاتی ہیں",
  "Wicks are often more informative than the body. A LONG UPPER WICK means price tried to go higher but was pushed back down by sellers — a warning sign for bulls. A LONG LOWER WICK means price tried to drop but buyers stepped in and rescued it — a bullish signal. SHORT WICKS on both sides mean price moved decisively in one direction — strong conviction.": "وِکس اکثر باڈی سے زیادہ معلوماتی ہوتی ہیں۔ ایک لمبی اوپری وِک کا مطلب ہے کہ قیمت اوپر جانے کی کوشش کر رہی تھی لیکن بیچنے والوں نے اسے واپس نیچے دھکیل دیا — بلز کے لیے ایک انتباہی علامت۔ ایک لمبی نچلی وِک کا مطلب ہے کہ قیمت گرنے کی کوشش کر رہی تھی لیکن خریداروں نے مداخلت کی اور اسے بچا لیا — ایک تیزی کا اشارہ۔ دونوں اطراف چھوٹی وِکس کا مطلب ہے کہ قیمت ایک سمت میں فیصلہ کن طور پر چلی — مضبوط یقین۔",
  "Never look at a single candlestick in isolation. One candle is just one data point. Patterns formed by 2-3 candles together are far more meaningful. Check the '5 Candle Patterns' lesson next.": "کسی ایک کینڈل سٹک کو کبھی بھی تنہائی میں نہ دیکھیں۔ ایک کینڈل صرف ایک ڈیٹا پوائنٹ ہے۔ 2-3 کینڈلز کے ذریعے بننے والے پیٹرن کہیں زیادہ معنی خیز ہوتے ہیں۔ اگلا '5 کینڈل پیٹرنز' سبق دیکھیں۔",
  "Why This Matters on PSX": "PSX پر یہ کیوں اہم ہے",
  "PSX stocks often show very clear candlestick signals because retail investor sentiment is strong. During the 2023 market recovery, the KSE-100 formed a textbook 'Morning Star' pattern (3 candles) that preceded a 4,000-point rally. Candlestick readers saw it coming.": "PSX کے اسٹاک اکثر بہت واضح کینڈل سٹک سگنلز دکھاتے ہیں کیونکہ ریٹیل سرمایہ کاروں کا جذبہ مضبوط ہوتا ہے۔ 2023 کی مارکیٹ ریکوری کے دوران، KSE-100 نے ایک نصابی 'مارننگ سٹار' پیٹرن (3 کینڈلز) بنایا جس کے بعد 4,000 پوائنٹس کی ریلی آئی۔ کینڈل سٹک پڑھنے والوں نے اسے آتے دیکھا۔",
  "Candlesticks describe what already happened — they hint at probabilities, not certainties. Always pair them with risk management like a stop-loss.": "کینڈل سٹکس بیان کرتی ہیں کہ کیا ہو چکا ہے — وہ امکانات کی طرف اشارہ کرتی ہیں، یقینیت کی طرف نہیں۔ انہیں ہمیشہ رسک مینجمنٹ جیسے کہ سٹاپ لاس کے ساتھ جوڑیں۔",
  "What does the BODY of a candlestick represent?": "کینڈل سٹک کی باڈی کیا ظاہر کرتی ہے؟",
  "The highest and lowest price of the day": "دن کی سب سے زیادہ اور سب سے کم قیمت",
  "The opening and closing price of the period": "مدت کی اوپننگ اور کلوزنگ قیمت",
  "The total volume traded": "کل ٹریڈ شدہ حجم",
  "The difference between two moving averages": "دو موونگ ایوریجز کے درمیان فرق",
  "The body (thick part) shows where price OPENED and CLOSED. The wicks/shadows show the HIGH and LOW extremes.": "باڈی (موٹا حصہ) دکھاتا ہے کہ قیمت کہاں کھلی اور بند ہوئی۔ وِکس/شیڈوز ہائی اور لو انتہاؤں کو دکھاتے ہیں۔",
  "A GREEN (teal) candlestick on NafaIQ means...": "NafaIQ پر ایک سبز (ٹیل) کینڈل سٹک کا مطلب ہے...",
  "The stock is halal certified": "اسٹاک حلال سرٹیفائیڈ ہے",
  "Trading volume was above average": "ٹریڈنگ حجم اوسط سے زیادہ تھا",
  "The closing price was LOWER than the opening price": "اختتامی قیمت ابتدائی قیمت سے کم تھی۔",
  "The closing price was HIGHER than the opening price": "اختتامی قیمت ابتدائی قیمت سے زیادہ تھی۔",
  "Green/teal = price closed higher than it opened = bullish (buying pressure). Red = closed lower = bearish.": "سبز/فیروزی = قیمت ابتدائی قیمت سے زیادہ پر بند ہوئی = تیزی (خریداری کا دباؤ)۔ سرخ = کم پر بند ہوئی = مندی۔",
  "On PSX, if HBL opened at 140 and closed at 145, the candlestick body would be...": "PSX پر، اگر HBL 140 پر کھلا اور 145 پر بند ہوا، تو کینڈل سٹک باڈی ہوگی...",
  "Red, spanning 140 to 145": "سرخ، 140 سے 145 تک پھیلی ہوئی",
  "Green, spanning 140 to 145": "سبز، 140 سے 145 تک پھیلی ہوئی",
  "Red, spanning 145 to 140": "سرخ، 145 سے 140 تک پھیلی ہوئی",
  "The color depends on volume, not price direction": "رنگ کا انحصار حجم پر ہوتا ہے، قیمت کی سمت پر نہیں۔",
  "Price went UP (140→145), so the candle is GREEN. Body runs from open (140) at bottom to close (145) at top.": "قیمت اوپر گئی (140→145)، لہذا کینڈل سبز ہے۔ باڈی نیچے اوپن (140) سے اوپر کلوز (145) تک چلتی ہے۔",
  "Understanding RSI": "RSI کو سمجھنا",
  "Reading momentum with the Relative Strength Index": "ریلیٹیو اسٹرینتھ انڈیکس کے ساتھ مومینٹم کو پڑھنا",
  "Technical Analysis": "تکنیکی تجزیہ",
  "What's RSI divergence?": "RSI ڈائیورجنس کیا ہے؟",
  "Best RSI settings for PSX?": "PSX کے لیے بہترین RSI سیٹنگز کیا ہیں؟",
  "Explain overbought vs oversold": "اوور باٹ بمقابلہ اوور سولڈ کی وضاحت کریں",
  "The Relative Strength Index (RSI) is a momentum oscillator that moves between 0 and 100. It helps you gauge whether a stock has been bought or sold too aggressively in the recent past.": "ریلیٹیو اسٹرینتھ انڈیکس (RSI) ایک مومینٹم آسیلیٹر ہے جو 0 اور 100 کے درمیان حرکت کرتا ہے۔ یہ آپ کو یہ اندازہ لگانے میں مدد کرتا ہے کہ آیا کسی اسٹاک کو حالیہ ماضی میں بہت زیادہ جارحانہ طریقے سے خریدا یا بیچا گیا ہے۔",
  "The default RSI period is 14. On PSX daily charts, RSI(14) works well for most blue-chip stocks like HBL and ENGRO.": "ڈیفالٹ RSI پیریڈ 14 ہے۔ PSX کے روزانہ چارٹس پر، RSI(14) HBL اور ENGRO جیسے زیادہ تر بلیو چپ اسٹاکس کے لیے اچھی طرح کام کرتا ہے۔",
  "The RSI Formula": "RSI فارمولا",
  "RSI compares the size of recent gains to recent losses:": "RSI حالیہ فوائد کے حجم کا حالیہ نقصانات سے موازنہ کرتا ہے:",
  "RSI = 100 - [100 / (1 + RS)]": "RSI = 100 - [100 / (1 + RS)]",
  "Where RS = Avg Gain / Avg Loss": "جہاں RS = اوسط فائدہ / اوسط نقصان",
  "Overbought and Oversold": "اوور باٹ اور اوور سولڈ",
  "An RSI above 70 is considered overbought (buying may be stretched), while below 30 is oversold (selling may be exhausted). These are warnings, not automatic buy/sell signals.": "70 سے اوپر کا RSI اوور باٹ سمجھا جاتا ہے (خریداری بڑھ سکتی ہے)، جبکہ 30 سے نیچے اوور سولڈ (فروخت ختم ہو سکتی ہے)۔ یہ انتباہات ہیں، خودکار خرید/فروخت کے سگنل نہیں۔",
  "In strong trends RSI can stay overbought or oversold for a long time. Never short a stock just because RSI is above 70.": "مضبوط رجحانات میں RSI طویل عرصے تک اوور باٹ یا اوور سولڈ رہ سکتا ہے۔ صرف اس لیے کسی اسٹاک کو شارٹ نہ کریں کہ RSI 70 سے اوپر ہے۔",
  "RSI stands for...": "RSI کا مطلب ہے...",
  "Relative Stability Index": "ریلیٹیو اسٹیبلٹی انڈیکس",
  "Return on Stock Investment": "اسٹاک انویسٹمنٹ پر منافع",
  "Relative Strength Index": "ریلیٹیو اسٹرینتھ انڈیکس",
  "Risk Sensitivity Indicator": "رسک سینسیٹیویٹی انڈیکیٹر",
  "RSI = Relative Strength Index. Developed by J. Welles Wilder in 1978. Measures momentum, not absolute strength.": "RSI = ریلیٹیو اسٹرینتھ انڈیکس۔ 1978 میں جے ویلز وائلڈر نے تیار کیا۔ یہ مومینٹم کی پیمائش کرتا ہے، مطلق طاقت کی نہیں۔",
  "An RSI reading of 78 on HBL most likely suggests...": "HBL پر 78 کا RSI ریڈنگ زیادہ تر یہ تجویز کرتی ہے کہ...",
  "HBL is in a strong downtrend": "HBL ایک مضبوط گراوٹ کے رجحان میں ہے",
  "HBL is oversold and may bounce": "HBL اوور سولڈ ہے اور اوپر جا سکتا ہے",
  "HBL is overbought and may face selling pressure": "HBL اوور باٹ ہے اور اسے فروخت کے دباؤ کا سامنا کرنا پڑ سکتا ہے",
  "HBL has very low trading volume": "HBL میں ٹریڈنگ کا حجم بہت کم ہے",
  "RSI above 70 = overbought zone. Does not mean sell immediately, but warns that buying momentum is stretched.": "RSI 70 سے اوپر = اوور باٹ زون۔ اس کا مطلب یہ نہیں کہ فوری طور پر فروخت کریں، لیکن یہ خبردار کرتا ہے کہ خریدنے کا مومینٹم بڑھ چکا ہے۔",
  "RSI of 25 on ENGRO in a downtrend typically signals...": "ایک گراوٹ کے رجحان میں ENGRO پر 25 کا RSI عام طور پر اشارہ کرتا ہے کہ...",
  "Sell immediately — trend will continue forever": "فوری طور پر فروخت کریں — رجحان ہمیشہ جاری رہے گا",
  "Oversold conditions — potential reversal or bounce": "اوور سولڈ حالات — ممکنہ پلٹاؤ یا اوپر جانا",
  "Overbought — price is too high": "اوور باٹ — قیمت بہت زیادہ ہے",
  "No signal — RSI below 30 is irrelevant": "کوئی سگنل نہیں — 30 سے نیچے کا RSI غیر متعلقہ ہے",
  "Below 30 = oversold. In a strong downtrend, RSI can stay low — but it warns of potential exhaustion of sellers.": "30 سے نیچے = اوور سولڈ۔ ایک مضبوط گراوٹ کے رجحان میں، RSI کم رہ سکتا ہے — لیکن یہ بیچنے والوں کی ممکنہ تھکن سے خبردار کرتا ہے۔",
  "What is a Stop-Loss?": "اسٹاپ لاس کیا ہے؟",
  "Protecting your capital with a planned exit": "منصوبہ بند اخراج کے ساتھ اپنے سرمائے کا تحفظ",
  "Risk Management": "رسک مینجمنٹ",
  "What's a trailing stop-loss?": "ٹریلنگ اسٹاپ لاس کیا ہے؟",
  "How to avoid stop hunts?": "اسٹاپ ہنٹس سے کیسے بچیں؟",
  "PSX circuit breaker vs stop-loss?": "PSX سرکٹ بریکر بمقابلہ اسٹاپ لاس؟",
  "A stop-loss is a pre-set order that automatically sells your position once price falls to a level you choose in advance. It is the single most important tool for protecting your capital.": "اسٹاپ لاس ایک پہلے سے طے شدہ آرڈر ہے جو خود بخود آپ کی پوزیشن کو فروخت کر دیتا ہے جب قیمت آپ کے پہلے سے منتخب کردہ سطح پر گر جاتی ہے۔ یہ آپ کے سرمائے کے تحفظ کے لیے سب سے اہم ٹول ہے۔",
  "Decide your stop-loss BEFORE you buy, while you are calm and objective — not after price is already falling.": "خریدنے سے پہلے اپنا اسٹاپ لاس طے کریں، جب آپ پرسکون اور معروضی ہوں — قیمت گرنے کے بعد نہیں۔",
  "How It Works": "یہ کیسے کام کرتا ہے",
  "If you buy LUCK at PKR 845 and set a stop-loss at PKR 820, your broker will trigger a sell order if price touches 820 — capping your loss at roughly PKR 25 per share.": "اگر آپ LUCK کو 845 روپے پر خریدتے ہیں اور 820 روپے پر سٹاپ لاس سیٹ کرتے ہیں، تو آپ کا بروکر 820 روپے پر قیمت پہنچنے پر فروخت کا آرڈر دے گا — جس سے آپ کا نقصان تقریباً 25 روپے فی شیئر تک محدود ہو جائے گا۔",
  "Max Loss = (Entry - Stop) × Shares": "زیادہ سے زیادہ نقصان = (خریداری کی قیمت - سٹاپ لاس) × شیئرز",
  "Example: (845 - 820) × 100 = PKR 2,500": "مثال: (845 - 820) × 100 = 2,500 روپے",
  "Where to Place It": "اسے کہاں رکھنا ہے",
  "Place your stop-loss just below a meaningful support level or recent swing low — the level where your reason for buying would no longer be valid. Arbitrary percentages are weaker than technical levels.": "اپنا سٹاپ لاس کسی اہم سپورٹ لیول یا حالیہ سوئنگ لو سے بالکل نیچے رکھیں — وہ لیول جہاں آپ کی خریداری کی وجہ مزید درست نہیں رہے گی۔ من مانی فیصد تکنیکی لیولز سے کمزور ہوتے ہیں۔",
  "In fast markets your stop may execute slightly below your level (slippage). Build a small buffer into your risk plan.": "تیز مارکیٹوں میں آپ کا سٹاپ آپ کے لیول سے تھوڑا نیچے عمل میں آ سکتا ہے (سلپیج)۔ اپنے رسک پلان میں ایک چھوٹا سا بفر شامل کریں۔",
  "What is the PRIMARY purpose of a stop-loss order?": "سٹاپ لاس آرڈر کا بنیادی مقصد کیا ہے؟",
  "To maximize profit on winning trades": "کامیاب ٹریڈز پر منافع کو زیادہ سے زیادہ کرنا",
  "To automatically buy more shares when price drops": "قیمت گرنے پر خود بخود مزید شیئرز خریدنا",
  "To limit your maximum loss on a position": "کسی پوزیشن پر اپنے زیادہ سے زیادہ نقصان کو محدود کرنا",
  "To predict when a stock will reverse direction": "یہ پیش گوئی کرنا کہ اسٹاک کب سمت بدلے گا",
  "Stop-loss = pre-set exit. You decide in advance how much loss you can accept. Removes emotion from the decision.": "سٹاپ لاس = پہلے سے طے شدہ ایگزٹ۔ آپ پہلے سے فیصلہ کرتے ہیں کہ آپ کتنا نقصان قبول کر سکتے ہیں۔ یہ فیصلے سے جذبات کو ہٹاتا ہے۔",
  "You buy LUCK at PKR 845. You set a stop-loss at PKR 820. If LUCK drops to 820, what happens?": "آپ LUCK کو 845 روپے پر خریدتے ہیں۔ آپ 820 روپے پر سٹاپ لاس سیٹ کرتے ہیں۔ اگر LUCK 820 پر گرتا ہے، تو کیا ہوتا ہے؟",
  "Nothing — you must manually sell": "کچھ نہیں — آپ کو دستی طور پر فروخت کرنا پڑے گا",
  "Your broker alerts you but waits for confirmation": "آپ کا بروکر آپ کو الرٹ کرتا ہے لیکن تصدیق کا انتظار کرتا ہے",
  "Your position is automatically sold at ~PKR 820": "آپ کی پوزیشن خود بخود تقریباً 820 روپے پر فروخت ہو جاتی ہے",
  "You automatically buy more LUCK at the lower price": "آپ خود بخود کم قیمت پر مزید LUCK خریدتے ہیں",
  "A stop-loss triggers a SELL order when price hits your set level. Execution may be slightly below 820 in fast markets (slippage).": "جب قیمت آپ کے مقرر کردہ لیول پر پہنچتی ہے تو سٹاپ لاس ایک SELL آرڈر کو متحرک کرتا ہے۔ تیز مارکیٹوں میں عمل درآمد 820 سے تھوڑا نیچے ہو سکتا ہے (سلپیج)۔",
  "Where should a stop-loss ideally be placed?": "سٹاپ لاس کو مثالی طور پر کہاں رکھنا چاہیے؟",
  "Exactly 5% below entry price, always": "ہمیشہ انٹری پرائس سے بالکل 5% نیچے",
  "Just below a key support level or recent swing low": "کسی اہم سپورٹ لیول یا حالیہ سوئنگ لو سے بالکل نیچے",
  "At your average cost price to break even": "بریک ایون کرنے کے لیے اپنی اوسط لاگت کی قیمت پر",
  "Stop-losses are only for beginners — experts don't use them": "سٹاپ لاس صرف ابتدائی افراد کے لیے ہیں — ماہرین انہیں استعمال نہیں کرتے",
  "Technical placement beats arbitrary percentages. Below support = the level where your trade thesis is invalidated.": "تکنیکی پلیسمنٹ من مانی فیصد سے بہتر ہے۔ سپورٹ سے نیچے = وہ لیول جہاں آپ کا ٹریڈ تھیسس غلط ثابت ہو جاتا ہے۔",
  "Dividend Yield": "ڈیویڈنڈ ییلڈ",
  "Measuring the income a stock pays you": "یہ جانچنا کہ ایک اسٹاک آپ کو کتنی آمدنی دیتا ہے",
  "Fundamentals": "بنیادی عوامل",
  "What is a payout ratio?": "پے آؤٹ ریشو کیا ہے؟",
  "Best dividend stocks on PSX?": "PSX پر بہترین ڈیویڈنڈ اسٹاک کون سے ہیں؟",
  "Are dividends taxed in Pakistan?": "کیا پاکستان میں ڈیویڈنڈ پر ٹیکس لگتا ہے؟",
  "Dividend yield tells you how much cash income a stock pays relative to its price. It is the favourite metric of income-focused PSX investors who want regular returns, not just capital gains.": "ڈیویڈنڈ ییلڈ آپ کو بتاتی ہے کہ ایک اسٹاک اپنی قیمت کے لحاظ سے کتنی نقد آمدنی دیتا ہے۔ یہ PSX کے ان سرمایہ کاروں کا پسندیدہ پیمانہ ہے جو باقاعدہ منافع چاہتے ہیں، نہ کہ صرف کیپیٹل گین۔",
  "High-dividend PSX names like FFC and HUBCO are popular with retirees and conservative investors seeking steady payouts.": "FFC اور HUBCO جیسے زیادہ ڈیویڈنڈ دینے والے PSX اسٹاک ریٹائر ہونے والوں اور قدامت پسند سرمایہ کاروں میں مقبول ہیں جو مستحکم ادائیگیوں کی تلاش میں ہیں۔",
  "The Formula": "فارمولا",
  "Dividend yield is the annual dividend per share divided by the current price, expressed as a percentage:": "ڈیویڈنڈ ییلڈ فی شیئر سالانہ ڈیویڈنڈ کو موجودہ قیمت سے تقسیم کرنے پر حاصل ہوتی ہے، جسے فیصد میں ظاہر کیا جاتا ہے:",
  "Dividend Yield = (Annual Dividend / Share Price) × 100": "ڈیویڈنڈ ییلڈ = (سالانہ ڈیویڈنڈ / شیئر کی قیمت) × 100",
  "Example: (16 / 168) × 100 = 9.52%": "مثال: (16 / 168) × 100 = 9.52%",
  "Price and Yield Move Opposite": "قیمت اور ییلڈ مخالف سمت میں حرکت کرتے ہیں",
  "Because price is the denominator, a rising share price (with the same dividend) lowers the yield, and a falling price raises it. A very high yield can sometimes be a warning that the market expects a dividend cut.": "چونکہ قیمت ڈینومینیٹر ہے، شیئر کی بڑھتی ہوئی قیمت (اسی ڈیویڈنڈ کے ساتھ) ییلڈ کو کم کرتی ہے، اور گرتی ہوئی قیمت اسے بڑھاتی ہے۔ بہت زیادہ ییلڈ بعض اوقات اس بات کی وارننگ ہو سکتی ہے کہ مارکیٹ ڈیویڈنڈ میں کٹوتی کی توقع کر رہی ہے۔",
  "An unusually high yield is not always good news — check whether the company can actually sustain the payout.": "غیر معمولی طور پر زیادہ ییلڈ ہمیشہ اچھی خبر نہیں ہوتی — چیک کریں کہ کیا کمپنی واقعی ادائیگی کو برقرار رکھ سکتی ہے۔",
  "Dividend Yield formula is...": "ڈیویڈنڈ ییلڈ کا فارمولا ہے...",
  "Share Price ÷ Annual Dividend": "شیئر کی قیمت ÷ سالانہ ڈیویڈنڈ",
  "Annual Dividend × Share Price": "سالانہ ڈیویڈنڈ × شیئر کی قیمت",
  "Annual Dividend ÷ Share Price × 100": "سالانہ ڈیویڈنڈ ÷ شیئر کی قیمت × 100",
  "Net Profit ÷ Total Shares": "خالص منافع ÷ کل شیئرز",
  "Yield = (Annual DPS / Current Price) × 100. If FFC pays PKR 16/share and trades at 168, yield = 9.5%.": "ییلڈ = (سالانہ DPS / موجودہ قیمت) × 100۔ اگر FFC PKR 16/شیئر ادا کرتا ہے اور 168 پر ٹریڈ کر رہا ہے، تو ییلڈ = 9.5%۔",
  "FFC pays PKR 16 dividend. Current price is PKR 168. What is the dividend yield?": "FFC PKR 16 ڈیویڈنڈ ادا کرتا ہے۔ موجودہ قیمت PKR 168 ہے۔ ڈیویڈنڈ ییلڈ کیا ہے؟",
  "16%": "16%",
  "9.52%": "9.52%",
  "168%": "168%",
  "10.5%": "10.5%",
  "(16 ÷ 168) × 100 = 9.52%. FFC is known as a high-dividend stock on PSX — attractive for income investors.": "(16 ÷ 168) × 100 = 9.52%۔ FFC کو PSX پر ایک ہائی ڈیویڈنڈ اسٹاک کے طور پر جانا جاتا ہے — جو آمدنی کے سرمایہ کاروں کے لیے پرکشش ہے۔",
  "If a stock's PRICE rises but dividend stays the same...": "اگر کسی اسٹاک کی قیمت بڑھتی ہے لیکن ڈیویڈنڈ وہی رہتا ہے...",
  "Dividend yield increases": "ڈیویڈنڈ ییلڈ بڑھ جاتی ہے",
  "Dividend yield stays the same": "ڈیویڈنڈ ییلڈ وہی رہتی ہے",
  "Dividend yield decreases": "ڈیویڈنڈ ییلڈ کم ہو جاتی ہے",
  "The company must increase its dividend": "کمپنی کو اپنا ڈیویڈنڈ بڑھانا چاہیے",
  "Yield = dividend ÷ price. Higher price = lower yield (same numerator, bigger denominator). Inverse relationship.": "ییلڈ = ڈیویڈنڈ ÷ قیمت۔ زیادہ قیمت = کم ییلڈ (وہی نیومریٹر، بڑا ڈینومینیٹر)۔ الٹا تعلق۔",
  "Sector Heatmap Guide": "سیکٹر ہیٹ میپ گائیڈ",
  "Spotting market rotation at a glance": "مارکیٹ روٹیشن کو ایک نظر میں پہچاننا",
  "What is sector rotation?": "سیکٹر روٹیشن کیا ہے؟",
  "Why are banks green today?": "آج بینک سبز کیوں ہیں؟",
  "How often does the heatmap update?": "ہیٹ میپ کتنی بار اپ ڈیٹ ہوتا ہے؟",
  "Reading the Colours": "رنگوں کو پڑھنا",
  "A sector heatmap shows the whole market on one screen. Each tile is a sector or stock; its colour shows performance — green for gains, red for losses — and its size usually reflects market weight. One glance tells you where money is flowing today.": "ایک سیکٹر ہیٹ میپ پوری مارکیٹ کو ایک اسکرین پر دکھاتا ہے۔ ہر ٹائل ایک سیکٹر یا اسٹاک ہے؛ اس کا رنگ کارکردگی کو ظاہر کرتا ہے — سبز منافع کے لیے، سرخ نقصان کے لیے — اور اس کا سائز عام طور پر مارکیٹ ویٹ کی عکاسی کرتا ہے۔ ایک نظر میں آپ کو معلوم ہو جاتا ہے کہ آج پیسہ کہاں بہہ رہا ہے۔",
  "Deeper green or red means a bigger move. A pale tile is roughly flat, not necessarily 'safe' — it just hasn't moved much.": "گہرا سبز یا سرخ ایک بڑی حرکت کا مطلب ہے۔ ایک ہلکا ٹائل تقریباً فلیٹ ہے، ضروری نہیں کہ 'محفوظ' ہو — یہ صرف زیادہ حرکت نہیں کیا ہے۔",
  "Spotting Sector Rotation": "سیکٹر روٹیشن کو پہچاننا",
  "Markets move in rotations — money leaves one sector and crowds into another. When banks are deep green while cement and autos bleed red, capital is rotating toward financials. The heatmap makes that shift obvious before headlines explain it.": "مارکیٹیں روٹیشن میں حرکت کرتی ہیں — پیسہ ایک سیکٹر سے نکل کر دوسرے میں جمع ہوتا ہے۔ جب بینک گہرے سبز ہوں جبکہ سیمنٹ اور آٹوز سرخ رنگ میں خون بہا رہے ہوں، تو سرمایہ فنانشلز کی طرف منتقل ہو رہا ہے۔ ہیٹ میپ اس تبدیلی کو سرخیوں کے بیان کرنے سے پہلے ہی واضح کر دیتا ہے۔",
  "If oil & gas tiles turn green across the board after a crude price jump, that's sector-wide momentum — not a one-stock story.": "اگر خام تیل کی قیمت میں اضافے کے بعد آئل اینڈ گیس کے ٹائلز ہر جگہ سبز ہو جائیں، تو یہ سیکٹر وائیڈ مومینٹم ہے — نہ کہ ایک اسٹاک کی کہانی۔",
  "Using It Without Being Fooled": "اسے دھوکہ کھائے بغیر استعمال کرنا",
  "The heatmap is a starting point, not a buy list. A green sector tells you where attention is, but you still confirm the individual stock's chart and fundamentals before acting.": "ہیٹ میپ ایک ابتدائی نقطہ ہے، نہ کہ خریدنے کی فہرست۔ ایک سبز سیکٹر آپ کو بتاتا ہے کہ توجہ کہاں ہے، لیکن آپ عمل کرنے سے پہلے انفرادی اسٹاک کے چارٹ اور بنیادی اصولوں کی تصدیق کرتے ہیں۔",
  "A single green day doesn't make a trend. Don't chase a hot sector at the top — confirm with a few sessions of follow-through.": "ایک دن کی سبز رنگت رجحان نہیں بناتی۔ کسی گرم سیکٹر کا پیچھا نہ کریں جب وہ عروج پر ہو — چند سیشنز کے فالو تھرو سے تصدیق کریں۔",
  "On a sector heatmap, what does a deep red tile indicate?": "ایک سیکٹر ہیٹ میپ پر، ایک گہرا سرخ ٹائل کیا ظاہر کرتا ہے؟",
  "A large gain": "ایک بڑا فائدہ",
  "A large loss": "ایک بڑا نقصان",
  "No change": "کوئی تبدیلی نہیں",
  "A halted stock": "ایک رکا ہوا اسٹاک",
  "Red means a decline, and a deeper shade indicates a bigger loss.": "سرخ کا مطلب گراوٹ ہے، اور گہرا شیڈ زیادہ نقصان کی نشاندہی کرتا ہے۔",
  "Banks are green while autos and cement are red. What is this likely showing?": "بینکس سبز ہیں جبکہ آٹوز اور سیمنٹ سرخ ہیں۔ یہ ممکنہ طور پر کیا دکھا رہا ہے؟",
  "A data error": "ایک ڈیٹا کی خرابی",
  "Sector rotation toward financials": "فنانشلز کی طرف سیکٹر روٹیشن",
  "The market is closed": "مارکیٹ بند ہے",
  "Nothing meaningful": "کچھ بھی معنی خیز نہیں",
  "Money moving into one sector while leaving others is classic sector rotation.": "ایک سیکٹر میں پیسہ منتقل ہونا جبکہ دوسروں سے نکلنا کلاسک سیکٹر روٹیشن ہے۔",
  "How should you treat a hot green sector on the heatmap?": "ہیٹ میپ پر ایک گرم سبز سیکٹر کے ساتھ آپ کو کیسا سلوک کرنا چاہیے؟",
  "Buy any stock in it immediately": "اس میں موجود کسی بھی اسٹاک کو فوراً خرید لیں",
  "As a starting point — confirm the individual stock before acting": "ایک ابتدائی نقطہ کے طور پر — عمل کرنے سے پہلے انفرادی اسٹاک کی تصدیق کریں",
  "Ignore it completely": "اسے مکمل طور پر نظر انداز کریں",
  "Assume it will fall tomorrow": "فرض کریں کہ یہ کل گرے گا",
  "The heatmap shows where attention is; you still confirm the specific stock's chart and fundamentals.": "ہیٹ میپ دکھاتا ہے کہ توجہ کہاں ہے؛ آپ پھر بھی مخصوص اسٹاک کے چارٹ اور بنیادی اصولوں کی تصدیق کرتے ہیں۔",
  "5 Candle Patterns": "5 کینڈل پیٹرنز",
  "High-probability setups every trader should know": "اعلیٰ امکان والے سیٹ اپس جو ہر ٹریڈر کو معلوم ہونے چاہئیں",
  "What is a Morning Star?": "مارننگ اسٹار کیا ہے؟",
  "How reliable are patterns?": "پیٹرنز کتنے قابل اعتماد ہیں؟",
  "Bullish vs bearish engulfing?": "بلش بمقابلہ بیئرش اینگلفنگ؟",
  "Why Patterns Work": "پیٹرنز کیوں کام کرتے ہیں",
  "Candle patterns are short, repeatable shapes that hint at a shift in who's winning — buyers or sellers. They don't predict the future; they summarise a tug-of-war in price so you can act with more context than a single candle gives.": "کینڈل پیٹرنز مختصر، دہرائے جانے والے اشکال ہیں جو اس بات کی طرف اشارہ کرتے ہیں کہ کون جیت رہا ہے — خریدار یا بیچنے والے۔ وہ مستقبل کی پیش گوئی نہیں کرتے؛ وہ قیمت میں ایک رسہ کشی کا خلاصہ کرتے ہیں تاکہ آپ ایک کینڈل کے مقابلے میں زیادہ سیاق و سباق کے ساتھ عمل کر سکیں۔",
  "A pattern at a key level (support, resistance, a moving average) is far more meaningful than the same pattern in the middle of nowhere.": "ایک اہم سطح (سپورٹ، مزاحمت، ایک موونگ ایوریج) پر ایک پیٹرن کہیں بھی بیچ میں اسی پیٹرن سے کہیں زیادہ معنی خیز ہوتا ہے۔",
  "The Five to Know": "جاننے کے لیے پانچ",
  "Master these five and you'll recognise the majority of high-probability setups on PSX charts.": "ان پانچ میں مہارت حاصل کریں اور آپ PSX چارٹس پر زیادہ تر اعلیٰ امکان والے سیٹ اپس کو پہچان لیں گے۔",
  "Pattern": "پیٹرن",
  "Signals": "سگنلز",
  "What it means": "اس کا کیا مطلب ہے",
  "Bullish Engulfing": "بلش اینگلفنگ",
  "Reversal up": "ریورسل اپ",
  "A big green candle swallows the prior red one": "ایک بڑی سبز کینڈل پچھلی سرخ کینڈل کو نگل لیتی ہے",
  "Bearish Engulfing": "بیئرش اینگلفنگ",
  "Reversal down": "ریورسل ڈاؤن",
  "A big red candle swallows the prior green one": "ایک بڑی سرخ کینڈل پچھلی سبز کینڈل کو نگل لیتی ہے",
  "Hammer": "ہتھوڑا",
  "Long lower wick — sellers pushed down, buyers won back": "لمبی نچلی وِک — بیچنے والوں نے نیچے دھکیلا، خریداروں نے واپس جیت لیا",
  "Shooting Star": "شوٹنگ اسٹار",
  "Long upper wick — buyers pushed up, sellers reclaimed": "لمبی اوپری وِک — خریداروں نے اوپر دھکیلا، بیچنے والوں نے واپس لے لیا",
  "Morning Star": "مارننگ اسٹار",
  "Three candles: drop, pause, strong recovery": "تین کینڈلز: گراوٹ، توقف، مضبوط ریکوری",
  "A hammer forming right at a stock's prior support level, on rising volume, is a classic 'buyers are stepping in' signal.": "ایک ہتھوڑا جو اسٹاک کے پچھلے سپورٹ لیول پر، بڑھتے ہوئے والیوم کے ساتھ بن رہا ہو، ایک کلاسک 'خریدار قدم رکھ رہے ہیں' سگنل ہے۔",
  "Confirm Before You Act": "عمل کرنے سے پہلے تصدیق کریں",
  "A pattern is a hint, not a trigger. The strongest signals are confirmed by volume and by the next candle continuing in the expected direction. On a thin PSX small-cap, a single candle can be noise.": "ایک پیٹرن ایک اشارہ ہے، ٹریگر نہیں۔ سب سے مضبوط سگنلز کی تصدیق والیوم اور اگلی کینڈل کے متوقع سمت میں جاری رہنے سے ہوتی ہے۔ ایک پتلی PSX سمال کیپ پر، ایک کینڈل شور ہو سکتی ہے۔",
  "Never trade a pattern in isolation. Wait for confirmation and always pair it with a stop-loss to cap the cost of being wrong.": "کسی بھی پیٹرن پر اکیلے ٹریڈ نہ کریں۔ تصدیق کا انتظار کریں اور غلط ہونے کی قیمت کو محدود کرنے کے لیے اسے ہمیشہ اسٹاپ لاس کے ساتھ جوڑیں۔",
  "What does a bullish engulfing pattern look like?": "بلش اینگلفنگ پیٹرن کیسا لگتا ہے؟",
  "A small green candle inside a large red one": "ایک چھوٹی سبز کینڈل ایک بڑی سرخ کینڈل کے اندر",
  "A large green candle that fully covers the prior red candle's body": "ایک بڑی سبز کینڈل جو پچھلی سرخ کینڈل کی باڈی کو مکمل طور پر ڈھانپ لیتی ہے",
  "Two red candles in a row": "لگاتار دو سرخ کینڈلز",
  "A single candle with no wicks": "کوئی وِک نہ ہونے والی ایک کینڈل",
  "Bullish engulfing is a large green candle whose body swallows the previous red candle — a reversal-up signal.": "بلش اینگلفنگ ایک بڑی سبز کینڈل ہے جس کی باڈی پچھلی سرخ کینڈل کو نگل لیتی ہے — ایک ریورسل-اپ سگنل۔",
  "A candle with a long lower wick and small body near support is a…": "ایک لمبی نچلی وِک اور سپورٹ کے قریب چھوٹی باڈی والی کینڈل ایک…",
  "Doji of no meaning": "بے معنی ڈوجی",
  "A long lower wick means sellers pushed price down but buyers reclaimed it — a hammer, especially strong at support.": "ایک لمبی نچلی وِک کا مطلب ہے کہ بیچنے والوں نے قیمت کو نیچے دھکیل دیا لیکن خریداروں نے اسے واپس حاصل کر لیا — ایک ہتھوڑا، خاص طور پر سپورٹ پر مضبوط۔",
  "What makes a candle pattern more trustworthy?": "ایک کینڈل پیٹرن کو کیا چیز زیادہ قابل اعتماد بناتی ہے؟",
  "Appearing in the middle of a range with low volume": "کم والیوم کے ساتھ رینج کے بیچ میں ظاہر ہونا",
  "Confirmation from volume and the following candle, at a key level": "والیوم اور اگلی کینڈل سے تصدیق، ایک اہم سطح پر",
  "Being on a very thin small-cap": "ایک بہت ہی پتلی سمال کیپ پر ہونا",
  "Ignoring all other signals": "دیگر تمام سگنلز کو نظر انداز کرنا",
  "Patterns are strongest when they form at key levels and are confirmed by volume and follow-through.": "پیٹرنز سب سے زیادہ مضبوط ہوتے ہیں جب وہ اہم سطحوں پر بنتے ہیں اور والیوم اور فالو تھرو سے تصدیق ہوتے ہیں۔",
  "50/30/20 Budget Rule": "50/30/20 بجٹ کا اصول",
  "A simple framework for managing your salary": "اپنی تنخواہ کا انتظام کرنے کے لیے ایک سادہ فریم ورک",
  "Personal Finance": "ذاتی مالیات",
  "How do I start budgeting?": "میں بجٹ بنانا کیسے شروع کروں؟",
  "What counts as a 'want'?": "'خواہش' میں کیا شمار ہوتا ہے؟",
  "Adapting 50/30/20 for Pakistan?": "پاکستان کے لیے 50/30/20 کو اپنانا؟",
  "The Rule in One Line": "ایک سطر میں اصول",
  "The 50/30/20 rule splits your take-home salary into three buckets: 50% for needs, 30% for wants, and 20% for savings and debt repayment. It's popular because it's simple enough to actually stick to.": "50/30/20 کا اصول آپ کی خالص تنخواہ کو تین حصوں میں تقسیم کرتا ہے: 50% ضروریات کے لیے، 30% خواہشات کے لیے، اور 20% بچت اور قرض کی ادائیگی کے لیے۔ یہ مقبول ہے کیونکہ یہ اتنا سادہ ہے کہ اس پر عمل کرنا آسان ہے۔",
  "Salary 100,000 → Needs 50,000 | Wants 30,000 | Save 20,000": "تنخواہ 100,000 → ضروریات 50,000 | خواہشات 30,000 | بچت 20,000",
  "Needs vs Wants": "ضروریات بمقابلہ خواہشات",
  "The hard part is honest categorisation. A need is something you can't reasonably skip — rent, utilities, groceries, transport to work. A want is everything that makes life nicer but isn't essential.": "مشکل حصہ ایماندارانہ درجہ بندی ہے۔ ایک ضرورت وہ ہے جسے آپ معقول حد تک نہیں چھوڑ سکتے — کرایہ، یوٹیلیٹیز، گروسری، کام پر جانے کے لیے ٹرانسپورٹ۔ ایک خواہش وہ سب کچھ ہے جو زندگی کو بہتر بناتا ہے لیکن ضروری نہیں ہے۔",
  "Bucket": "بکٹ",
  "Share": "شیئر",
  "Examples": "مثالیں",
  "Needs": "ضروریات",
  "50%": "50%",
  "Rent, electricity, groceries, fuel, school fees": "کرایہ، بجلی، سودا سلف، ایندھن، اسکول فیس",
  "Wants": "خواہشات",
  "30%": "30%",
  "Dining out, subscriptions, new phone, travel": "باہر کھانا، سبسکرپشنز، نیا فون، سفر",
  "Save / repay": "بچت / قرض کی ادائیگی",
  "20%": "20%",
  "Emergency fund, investments, extra loan payments": "ایمرجنسی فنڈ، سرمایہ کاری، اضافی قرض کی ادائیگیاں",
  "A monthly Netflix plan is a want. The internet connection you need for work sits in needs — same bill category, different purpose.": "ایک ماہانہ نیٹ فلکس پلان ایک خواہش ہے۔ انٹرنیٹ کنکشن جو آپ کو کام کے لیے درکار ہے وہ ضروریات میں آتا ہے — ایک ہی بل کیٹیگری، مختلف مقصد۔",
  "Adapting It for Pakistan": "اسے پاکستان کے لیے ڈھالنا",
  "With high inflation, many Pakistani households find needs eat well above 50%. Treat the ratios as a target to move toward, not a pass/fail test — even shifting 5% from wants to savings compounds meaningfully over years.": "زیادہ مہنگائی کے ساتھ، بہت سے پاکستانی گھرانے ضروریات پر 50% سے کہیں زیادہ خرچ کرتے ہیں۔ ان تناسب کو ایک ہدف کے طور پر لیں جس کی طرف بڑھنا ہے، نہ کہ پاس/فیل ٹیسٹ — یہاں تک کہ خواہشات سے بچت کی طرف 5% کی تبدیلی بھی سالوں میں نمایاں طور پر بڑھتی ہے۔",
  "Automate the 20%: move it to savings or investments the day your salary lands, before you start spending.": "20% کو خودکار بنائیں: اسے بچت یا سرمایہ کاری میں منتقل کریں جس دن آپ کی تنخواہ آتی ہے، اس سے پہلے کہ آپ خرچ کرنا شروع کریں۔",
  "Under 50/30/20, how much of a PKR 80,000 salary goes to savings and debt repayment?": "50/30/20 کے تحت، PKR 80,000 کی تنخواہ میں سے کتنی رقم بچت اور قرض کی ادائیگی کے لیے جاتی ہے؟",
  "8,000": "8,000",
  "16,000": "16,000",
  "24,000": "24,000",
  "40,000": "40,000",
  "20% of 80,000 = 16,000 for savings and debt repayment.": "80,000 کا 20% = 16,000 بچت اور قرض کی ادائیگی کے لیے۔",
  "Which of these belongs in the 'needs' bucket?": "ان میں سے کون سا 'ضروریات' کے زمرے میں آتا ہے؟",
  "Weekend dining out": "ہفتے کے آخر میں باہر کھانا",
  "A streaming subscription": "ایک سٹریمنگ سبسکرپشن",
  "Rent and utilities": "کرایہ اور یوٹیلیٹیز",
  "An upgraded smartphone": "ایک اپ گریڈ شدہ اسمارٹ فون",
  "Rent and utilities are essential and can't reasonably be skipped — they're needs.": "کرایہ اور یوٹیلیٹیز ضروری ہیں اور انہیں معقول حد تک چھوڑا نہیں جا سکتا — یہ ضروریات ہیں۔",
  "What's the smartest way to apply the rule with high inflation?": "زیادہ مہنگائی کے ساتھ اس اصول کو لاگو کرنے کا سب سے ذہین طریقہ کیا ہے؟",
  "Abandon budgeting entirely": "بجٹ سازی کو مکمل طور پر ترک کر دیں",
  "Treat the ratios as a target and improve gradually": "ان تناسب کو ایک ہدف سمجھیں اور آہستہ آہستہ بہتر بنائیں۔",
  "Spend the savings bucket first": "سب سے پہلے بچت کی بالٹی استعمال کریں۔",
  "Put 100% into wants": "100% خواہشات میں لگائیں۔",
  "When needs exceed 50%, use the ratios as a direction to move toward rather than a strict pass/fail.": "جب ضروریات 50% سے بڑھ جائیں، تو تناسب کو ایک سخت پاس/فیل کے بجائے ایک سمت کے طور پر استعمال کریں جس کی طرف بڑھنا ہے۔",
  "How PSX Works": "PSX کیسے کام کرتا ہے",
  "The mechanics of the Pakistan Stock Exchange": "پاکستان اسٹاک ایکسچینج کے میکانکس",
  "What is the KSE-100?": "KSE-100 کیا ہے؟",
  "How do I open a CDC account?": "میں CDC اکاؤنٹ کیسے کھولوں؟",
  "What are trading hours?": "تجارتی اوقات کیا ہیں؟",
  "What the PSX Actually Is": "PSX دراصل کیا ہے",
  "The Pakistan Stock Exchange is the marketplace where shares of listed Pakistani companies are bought and sold. When you buy a share of a company like a PSX-listed bank or fertiliser maker, you own a small slice of that business and its future profits.": "پاکستان اسٹاک ایکسچینج وہ بازار ہے جہاں لسٹڈ پاکستانی کمپنیوں کے حصص خریدے اور بیچے جاتے ہیں۔ جب آپ کسی کمپنی جیسے PSX میں درج بینک یا کھاد بنانے والی کمپنی کا شیئر خریدتے ہیں، تو آپ اس کاروبار اور اس کے مستقبل کے منافع کا ایک چھوٹا سا حصہ کے مالک بن جاتے ہیں۔",
  "The KSE-100 is the benchmark index — it tracks 100 of the largest companies by market capitalisation and is the number you'll see quoted as 'the market'.": "KSE-100 ایک بینچ مارک انڈیکس ہے — یہ مارکیٹ کیپٹلائزیشن کے لحاظ سے 100 سب سے بڑی کمپنیوں کو ٹریک کرتا ہے اور یہ وہ نمبر ہے جسے آپ 'مارکیٹ' کے طور پر حوالہ دیتے ہوئے دیکھیں گے۔",
  "How a Trade Happens": "ایک ٹریڈ کیسے ہوتا ہے",
  "You can't trade directly on the exchange. You open an account with a licensed broker, who routes your order to the PSX. Your shares are held in a central electronic depository (the CDC) under your name — not physically with the broker.": "آپ براہ راست ایکسچینج پر ٹریڈ نہیں کر سکتے۔ آپ ایک لائسنس یافتہ بروکر کے ساتھ اکاؤنٹ کھولتے ہیں، جو آپ کے آرڈر کو PSX پر بھیجتا ہے۔ آپ کے شیئرز ایک مرکزی الیکٹرانک ڈپازٹری (CDC) میں آپ کے نام پر رکھے جاتے ہیں — جسمانی طور پر بروکر کے پاس نہیں۔",
  "Step": "مرحلہ",
  "Who": "کون",
  "What happens": "کیا ہوتا ہے",
  "1. Open account": "1. اکاؤنٹ کھولیں",
  "You + broker": "آپ + بروکر",
  "CDC sub-account is created in your name": "آپ کے نام پر CDC سب اکاؤنٹ بنایا جاتا ہے",
  "2. Place order": "2. آرڈر دیں",
  "You": "آپ",
  "Buy/sell at market or a limit price": "مارکیٹ یا ایک حد قیمت پر خریدیں/بیچیں",
  "3. Match & settle": "3. میچ اور سیٹل کریں",
  "PSX + NCCPL": "PSX + NCCPL",
  "Trade clears, settles on a T+2 basis": "ٹریڈ T+2 کی بنیاد پر کلیئر اور سیٹل ہوتی ہے۔",
  "Place a limit buy for a bank stock at PKR 120. If a seller is willing at 120 or lower, the order fills; otherwise it waits in the order book.": "بینک اسٹاک کے لیے PKR 120 پر لِمٹ بائے آرڈر لگائیں۔ اگر کوئی بیچنے والا 120 یا اس سے کم پر راضی ہو تو آرڈر پُر ہو جاتا ہے؛ ورنہ یہ آرڈر بُک میں انتظار کرتا ہے۔",
  "Hours, Circuit Breakers & Risk": "اوقات، سرکٹ بریکرز اور رسک",
  "PSX trades on weekdays during set hours, and individual stocks have daily price limits (circuit breakers) that cap how far they can move in one session — a mechanism designed to slow panic in a retail-heavy market.": "PSX مقررہ اوقات کے دوران ہفتے کے دنوں میں ٹریڈ کرتا ہے، اور انفرادی اسٹاکس کی روزانہ کی قیمت کی حدیں (سرکٹ بریکرز) ہوتی ہیں جو ایک سیشن میں ان کی حرکت کو محدود کرتی ہیں — یہ ایک ایسا طریقہ کار ہے جو ریٹیل ہیوی مارکیٹ میں گھبراہٹ کو کم کرنے کے لیے ڈیزائن کیا گیا ہے۔",
  "Retail sentiment moves PSX fast. A stock hitting its upper or lower circuit can trap you in or out of a position — size your trades accordingly.": "ریٹیل سینٹیمنٹ PSX کو تیزی سے حرکت دیتا ہے۔ ایک اسٹاک کا اپنی اوپری یا نچلی سرکٹ کو چھونا آپ کو پوزیشن میں پھنسا سکتا ہے یا باہر نکال سکتا ہے — اپنی ٹریڈز کو اسی کے مطابق سائز کریں۔",
  "What does the KSE-100 measure?": "KSE-100 کیا پیمائش کرتا ہے؟",
  "The 100 cheapest stocks on PSX": "PSX پر 100 سستے ترین اسٹاکس",
  "100 of the largest PSX companies by market capitalisation": "مارکیٹ کیپٹلائزیشن کے لحاظ سے 100 سب سے بڑی PSX کمپنیاں",
  "All companies listed in Pakistan": "پاکستان میں درج تمام کمپنیاں",
  "Only banking sector stocks": "صرف بینکنگ سیکٹر کے اسٹاکس",
  "The KSE-100 is the benchmark index of 100 large companies, widely quoted as 'the market'.": "KSE-100 100 بڑی کمپنیوں کا بینچ مارک انڈیکس ہے، جسے عام طور پر 'مارکیٹ' کہا جاتا ہے۔",
  "Where are your PSX shares held after you buy them?": "آپ کے PSX شیئرز خریدنے کے بعد کہاں رکھے جاتے ہیں؟",
  "Physically with your broker": "جسمانی طور پر آپ کے بروکر کے پاس",
  "In an electronic CDC sub-account in your name": "آپ کے نام پر ایک الیکٹرانک CDC سب اکاؤنٹ میں",
  "At the company's head office": "کمپنی کے ہیڈ آفس میں",
  "In your bank account": "آپ کے بینک اکاؤنٹ میں",
  "Shares sit in the Central Depository Company electronically, registered to you — not held by the broker.": "شیئرز سینٹرل ڈیپازٹری کمپنی میں الیکٹرانک طور پر آپ کے نام پر رجسٹرڈ ہوتے ہیں — بروکر کے پاس نہیں ہوتے۔",
  "What is the purpose of a circuit breaker on a PSX stock?": "PSX اسٹاک پر سرکٹ بریکر کا مقصد کیا ہے؟",
  "To guarantee profits": "منافع کی ضمانت دینا",
  "To cap how far a stock's price can move in a single session": "ایک ہی سیشن میں اسٹاک کی قیمت کی حرکت کو محدود کرنا",
  "To set the dividend": "ڈیویڈنڈ مقرر کرنا",
  "To open new trading accounts": "نئے ٹریڈنگ اکاؤنٹس کھولنا",
  "Circuit breakers limit a stock's daily price move to slow panic-driven swings.": "سرکٹ بریکرز اسٹاک کی روزانہ کی قیمت کی حرکت کو محدود کرتے ہیں تاکہ گھبراہٹ سے چلنے والے اتار چڑھاؤ کو کم کیا جا سکے۔",
  "Halal Investing & Islamic Finance": "حلال سرمایہ کاری اور اسلامی فنانس",
  "Sharia-compliant principles for the modern investor": "جدید سرمایہ کار کے لیے شرعی اصول",
  "Islamic Finance": "اسلامی فنانس",
  "What makes a stock halal?": "کون سی چیز اسٹاک کو حلال بناتی ہے؟",
  "What is the KMI-30 index?": "KMI-30 انڈیکس کیا ہے؟",
  "Is interest income allowed?": "کیا سود کی آمدنی کی اجازت ہے؟",
  "What Makes Investing Halal": "سرمایہ کاری کو حلال کیا بناتا ہے",
  "Halal investing applies Islamic principles to the stock market. The core rules: avoid riba (interest), avoid excessive gharar (uncertainty/speculation), and avoid owning businesses whose core activity is haram — such as conventional banking, alcohol, gambling, or pork.": "حلال سرمایہ کاری اسٹاک مارکیٹ پر اسلامی اصولوں کا اطلاق کرتی ہے۔ بنیادی اصول: ربا (سود) سے بچیں، ضرورت سے زیادہ غرر (غیر یقینی/قیاس آرائی) سے بچیں، اور ایسے کاروباروں کی ملکیت سے گریز کریں جن کی بنیادی سرگرمی حرام ہے — جیسے روایتی بینکنگ، شراب، جوا، یا سور کا گوشت۔",
  "On PSX, the KMI-30 and KMI All-Share indices track companies screened as Sharia-compliant, so you don't have to vet every stock from scratch.": "PSX پر، KMI-30 اور KMI آل شیئر انڈیکس ایسی کمپنیوں کو ٹریک کرتے ہیں جنہیں شرعی اصولوں کے مطابق جانچا گیا ہے، لہذا آپ کو ہر اسٹاک کو شروع سے جانچنے کی ضرورت نہیں ہے۔",
  "The Screening Tests": "اسکریننگ ٹیسٹ",
  "A stock is screened on two levels. First, its business must be permissible. Second, its finances must pass quantitative thresholds — a company can run a halal business but still fail if it carries too much interest-based debt.": "ایک اسٹاک کو دو سطحوں پر جانچا جاتا ہے۔ سب سے پہلے، اس کا کاروبار جائز ہونا چاہیے۔ دوسرا، اس کے مالیات کو مقداری حدوں سے گزرنا چاہیے — ایک کمپنی حلال کاروبار چلا سکتی ہے لیکن پھر بھی ناکام ہو سکتی ہے اگر اس پر بہت زیادہ سود پر مبنی قرض ہو۔",
  "Screen": "اسکرین",
  "Common threshold": "عام حد",
  "Why it exists": "یہ کیوں موجود ہے",
  "Interest-bearing debt ÷ assets": "سود پر مبنی قرض ÷ اثاثے",
  "< 37%": "< 37%",
  "Limits reliance on riba-based borrowing": "ربا پر مبنی قرض پر انحصار کو محدود کرتا ہے",
  "Interest income ÷ revenue": "سود کی آمدنی ÷ آمدنی",
  "< 5%": "< 5%",
  "Keeps haram income immaterial": "حرام آمدنی کو غیر اہم رکھتا ہے",
  "Non-compliant investments": "غیر مطابق سرمایہ کاری",
  "Below set limit": "مقررہ حد سے کم",
  "Avoids indirect haram exposure": "بالواسطہ حرام نمائش سے بچتا ہے",
  "A profitable cement maker may still fail the screen if most of its balance sheet is funded by conventional interest-bearing loans.": "ایک منافع بخش سیمنٹ بنانے والا اب بھی اسکرین میں ناکام ہو سکتا ہے اگر اس کی بیلنس شیٹ کا زیادہ تر حصہ روایتی سود پر مبنی قرضوں سے فنڈ کیا گیا ہو۔",
  "Income Purification": "آمدنی کی تطہیر",
  "Even compliant companies may earn a tiny share of income from interest. Scholars require investors to 'purify' this by donating the equivalent proportion of their dividends to charity, keeping the remaining return halal.": "حتیٰ کہ شرعی اصولوں کے مطابق کمپنیاں بھی سود سے آمدنی کا ایک چھوٹا حصہ کما سکتی ہیں۔ علماء سرمایہ کاروں سے مطالبہ کرتے ہیں کہ وہ اس کی 'تطہیر' کریں اور اپنے منافع کا مساوی حصہ خیرات میں دیں، باقی منافع کو حلال رکھیں۔",
  "Screening status can change as a company's debt levels shift. Re-check compliance periodically rather than assuming it's permanent.": "اسکریننگ کی حیثیت کمپنی کے قرض کی سطح میں تبدیلی کے ساتھ بدل سکتی ہے۔ مستقل سمجھنے کے بجائے وقتاً فوقتاً تعمیل کو دوبارہ چیک کریں۔",
  "Which index on PSX tracks Sharia-compliant companies?": "PSX پر کون سا انڈیکس شرعی اصولوں کے مطابق کمپنیوں کو ٹریک کرتا ہے؟",
  "KSE-100": "KSE-100",
  "KMI-30": "KMI-30",
  "KSE-30": "KSE-30",
  "BR Index": "BR انڈیکس",
  "The KMI-30 (and KMI All-Share) track Sharia-screened PSX companies.": "KMI-30 (اور KMI آل شیئر) شرعی اصولوں کے مطابق PSX کمپنیوں کو ٹریک کرتے ہیں۔",
  "A company runs a permissible business but funds itself mostly with interest-bearing loans. Is it halal to invest in?": "ایک کمپنی ایک جائز کاروبار چلاتی ہے لیکن زیادہ تر سود پر مبنی قرضوں سے خود کو فنڈ کرتی ہے۔ کیا اس میں سرمایہ کاری کرنا حلال ہے؟",
  "Yes — the business activity is all that matters": "ہاں — صرف کاروباری سرگرمی ہی اہمیت رکھتی ہے",
  "Not necessarily — it can fail the financial debt screen": "ضروری نہیں — یہ مالی قرض کی اسکرین میں ناکام ہو سکتی ہے",
  "Yes — debt is never part of screening": "ہاں — قرض کبھی بھی اسکریننگ کا حصہ نہیں ہوتا",
  "Only if it pays a dividend": "صرف اگر یہ ڈیویڈنڈ ادا کرتی ہے",
  "Both the business and its finances are screened. Excessive interest-based debt can disqualify a permissible business.": "کاروبار اور اس کے مالیات دونوں کی اسکریننگ کی جاتی ہے۔ ضرورت سے زیادہ سود پر مبنی قرض ایک جائز کاروبار کو نااہل کر سکتا ہے۔",
  "What is 'purification' in halal investing?": "حلال سرمایہ کاری میں 'تزکیہ' کیا ہے؟",
  "Selling all stocks once a year": "سال میں ایک بار تمام اسٹاک فروخت کرنا",
  "Donating the share of returns linked to impermissible income": "ناجائز آمدنی سے منسلک منافع کا حصہ عطیہ کرنا",
  "Only buying KMI-30 stocks": "صرف KMI-30 اسٹاک خریدنا",
  "Avoiding dividends entirely": "ڈیویڈنڈ سے مکمل طور پر گریز کرنا",
  "Purification means giving away the proportion of income tied to non-compliant sources, such as small interest earnings.": "تزکیہ کا مطلب ہے غیر تعمیل ذرائع سے منسلک آمدنی کا تناسب دینا، جیسے کہ چھوٹی سود کی آمدنی۔",
  "Understanding P/E Ratio": "P/E ریشو کو سمجھنا",
  "Judging whether a stock is cheap or expensive": "یہ فیصلہ کرنا کہ آیا کوئی اسٹاک سستا ہے یا مہنگا",
  "What is a 'good' P/E?": "'اچھا' P/E کیا ہے؟",
  "Forward vs trailing P/E?": "فارورڈ بمقابلہ ٹریلنگ P/E؟",
  "P/E for PSX banks?": "PSX بینکوں کے لیے P/E؟",
  "What the P/E Ratio Tells You": "P/E ریشو آپ کو کیا بتاتا ہے",
  "The price-to-earnings (P/E) ratio answers one question: how many rupees are you paying for every one rupee of a company's annual profit? A P/E of 8 means the market values the stock at 8 times its yearly earnings per share.": "پرائس ٹو ارننگز (P/E) ریشو ایک سوال کا جواب دیتا ہے: آپ ایک کمپنی کے سالانہ منافع کے ہر ایک روپے کے لیے کتنے روپے ادا کر رہے ہیں؟ 8 کا P/E کا مطلب ہے کہ مارکیٹ اسٹاک کو اس کی فی شیئر سالانہ آمدنی کے 8 گنا پر قدر کرتی ہے۔",
  "P/E = Share Price ÷ Earnings Per Share (EPS)": "P/E = شیئر کی قیمت ÷ فی شیئر آمدنی (EPS)",
  "Example: 240 ÷ 30 = 8.0x": "مثال: 240 ÷ 30 = 8.0x",
  "EPS on PSX is usually reported annually in company financials. Most terminals show trailing EPS (last 12 months) by default.": "PSX پر EPS عام طور پر کمپنی کے مالیاتی گوشواروں میں سالانہ رپورٹ کیا جاتا ہے۔ زیادہ تر ٹرمینلز بطور ڈیفالٹ ٹریلنگ EPS (گزشتہ 12 ماہ) دکھاتے ہیں۔",
  "Cheap Isn't Always Good": "سستا ہمیشہ اچھا نہیں ہوتا",
  "A low P/E can mean a bargain — or a company the market expects to shrink. A high P/E can mean an overpriced stock — or one investors expect to grow fast. The number only has meaning when you compare a company to its own sector.": "کم P/E کا مطلب ایک سستا سودا ہو سکتا ہے — یا ایک ایسی کمپنی جس کے بارے میں مارکیٹ کو سکڑنے کی توقع ہے۔ ایک زیادہ P/E کا مطلب ایک مہنگا اسٹاک ہو سکتا ہے — یا ایک ایسا اسٹاک جس کے بارے میں سرمایہ کاروں کو تیزی سے بڑھنے کی توقع ہے۔ یہ عدد صرف اس وقت معنی رکھتا ہے جب آپ کسی کمپنی کا موازنہ اس کے اپنے شعبے سے کریں۔",
  "Stock type": "اسٹاک کی قسم",
  "Typical PSX P/E": "عام PSX P/E",
  "What it usually signals": "یہ عام طور پر کیا ظاہر کرتا ہے",
  "Mature bank": "پختہ بینک",
  "4–7x": "4–7x",
  "Steady earnings, low growth expectations": "مستحکم آمدنی، کم ترقی کی توقعات",
  "Cement / cyclical": "سیمنٹ / سائیکلیکل",
  "6–10x": "6–10x",
  "Earnings swing with the economic cycle": "معاشی چکر کے ساتھ آمدنی میں اتار چڑھاؤ",
  "Fast-growing tech/FMCG": "تیزی سے بڑھتی ہوئی ٹیک/FMCG",
  "15x+": "15x+",
  "Market is pricing in future growth": "مارکیٹ مستقبل کی ترقی کو قیمت میں شامل کر رہی ہے",
  "If a PSX bank trades at 4x while its peers average 7x, ask why. Sometimes it's an opportunity; sometimes the market sees a risk you haven't yet.": "اگر ایک PSX بینک 4x پر ٹریڈ کر رہا ہے جبکہ اس کے ہم منصب اوسطاً 7x پر ہیں، تو پوچھیں کیوں۔ کبھی کبھی یہ ایک موقع ہوتا ہے؛ کبھی کبھی مارکیٹ ایک ایسا خطرہ دیکھتی ہے جو آپ نے ابھی تک نہیں دیکھا۔",
  "Where P/E Breaks Down": "جہاں P/E ناکام ہو جاتا ہے",
  "P/E is useless when a company has no profit (negative EPS), and it can be distorted by one-off gains like asset sales. Always check whether the earnings are recurring before trusting the ratio.": "P/E بے کار ہے جب کسی کمپنی کو کوئی منافع نہ ہو (منفی EPS)، اور یہ اثاثوں کی فروخت جیسے یک طرفہ فوائد سے بگڑ سکتا ہے۔ تناسب پر بھروسہ کرنے سے پہلے ہمیشہ یہ چیک کریں کہ آیا آمدنی بار بار ہو رہی ہے۔",
  "A single-year P/E can be misleading for cyclical PSX sectors. Look at earnings across a full cycle, not just the latest result.": "ایک سال کا P/E سائیکلیکل PSX سیکٹرز کے لیے گمراہ کن ہو سکتا ہے۔ صرف تازہ ترین نتائج کے بجائے، پورے چکر میں آمدنی کو دیکھیں۔",
  "A stock trades at PKR 150 with an EPS of PKR 25. What is its P/E?": "ایک اسٹاک PKR 150 پر ٹریڈ کر رہا ہے جس کا EPS PKR 25 ہے۔ اس کا P/E کیا ہے؟",
  "3.75x": "3.75x",
  "6.0x": "6.0x",
  "25x": "25x",
  "150x": "150x",
  "P/E = price ÷ EPS = 150 ÷ 25 = 6.0x.": "P/E = قیمت ÷ EPS = 150 ÷ 25 = 6.0x۔",
  "A PSX bank has a P/E of 4 while the sector averages 7. What is the smartest read?": "ایک PSX بینک کا P/E 4 ہے جبکہ سیکٹر کا اوسط 7 ہے۔ سب سے بہترین تشریح کیا ہے؟",
  "It is automatically a bargain — buy immediately": "یہ خود بخود ایک سودا ہے — فوراً خریدیں",
  "Investigate why it's cheaper before concluding anything": "کوئی بھی نتیجہ اخذ کرنے سے پہلے تحقیق کریں کہ یہ سستا کیوں ہے",
  "It is overpriced and should be avoided": "یہ مہنگا ہے اور اس سے گریز کرنا چاہیے",
  "P/E never applies to banks": "P/E کبھی بھی بینکوں پر لاگو نہیں ہوتا",
  "A below-peer P/E is a prompt to investigate, not an automatic buy. The discount may reflect real risk.": "ہم مرتبہ سے کم P/E تحقیق کرنے کا اشارہ ہے، خود بخود خریدنے کا نہیں۔ یہ رعایت حقیقی خطرے کی عکاسی کر سکتی ہے۔",
  "When is the P/E ratio least reliable?": "P/E تناسب کب سب سے کم قابل اعتماد ہوتا ہے؟",
  "When the company has steady recurring profits": "جب کمپنی کے پاس مستحکم بار بار ہونے والے منافع ہوں",
  "When earnings are negative or boosted by one-off gains": "جب آمدنی منفی ہو یا یک طرفہ فوائد سے بڑھائی گئی ہو",
  "When comparing a company to its own sector": "جب کسی کمپنی کا موازنہ اس کے اپنے سیکٹر سے کیا جا رہا ہو",
  "When the stock pays a dividend": "جب اسٹاک ڈیویڈنڈ ادا کرتا ہو",
  "With no profit or distorted one-off earnings, P/E gives a misleading picture of value.": "منافع نہ ہونے یا یک طرفہ آمدنی کے ساتھ، P/E قدر کی گمراہ کن تصویر پیش کرتا ہے۔",
  "PSX Investor Starter": "PSX سرمایہ کار اسٹارٹر",
  "From zero to your first trade": "صفر سے آپ کی پہلی ٹریڈ تک",
  "Charts, patterns, and indicators": "چارٹس، پیٹرن، اور اشارے",
  "Halal investing principles": "حلال سرمایہ کاری کے اصول",
  "Budget, save, and grow": "بجٹ بنائیں، بچت کریں، اور ترقی کریں",
  "Bull Market": "بل مارکیٹ",
  "A market trending upward over a sustained period, driven by investor optimism.": "ایک مارکیٹ جو سرمایہ کاروں کی امید پرستی کی وجہ سے ایک طویل عرصے تک اوپر کی طرف رجحان رکھتی ہے۔",
  "Bear Market": "بیئر مارکیٹ",
  "A market in decline, typically a fall of 20% or more from recent highs.": "ایک مارکیٹ جو گراوٹ کا شکار ہو، عام طور پر حالیہ اونچائیوں سے 20% یا اس سے زیادہ کی گراوٹ۔",
  "Dividend": "ڈیویڈنڈ",
  "A share of company profit paid out to shareholders, usually in cash.": "کمپنی کے منافع کا ایک حصہ جو شیئر ہولڈرز کو ادا کیا جاتا ہے، عام طور پر نقد کی صورت میں۔",
  "Market Cap": "مارکیٹ کیپ",
  "Share price × total shares outstanding — the company's total market value.": "شیئر کی قیمت × کل بقایا شیئرز — کمپنی کی کل مارکیٹ ویلیو۔",
  "P/E Ratio": "P/E ریشو",
  "Price paid per rupee of earnings. A lower P/E may signal better value.": "فی روپے آمدنی پر ادا کی گئی قیمت۔ کم P/E بہتر ویلیو کا اشارہ دے سکتا ہے۔",
  "RSI": "RSI",
  "Momentum indicator from 0–100. Above 70 is overbought, below 30 oversold.": "0–100 سے مومینٹم انڈیکیٹر۔ 70 سے اوپر اوور باٹ ہے، 30 سے نیچے اوور سولڈ۔",
  "Volume": "والیوم",
  "Number of shares traded in a given period. High volume confirms moves.": "ایک مخصوص مدت میں ٹریڈ کیے گئے شیئرز کی تعداد۔ زیادہ والیوم حرکت کی تصدیق کرتا ہے۔",
  "Blue Chip": "بلیو چپ",
  "A large, stable, well-known company stock with a reliable track record.": "ایک بڑی، مستحکم، معروف کمپنی کا اسٹاک جس کا قابل اعتماد ٹریک ریکارڈ ہو۔",
  "Stop Loss": "اسٹاپ لاس",
  "An automatic sell order placed to limit losses on a position.": "کسی پوزیشن پر نقصانات کو محدود کرنے کے لیے دیا گیا خودکار فروخت کا آرڈر۔",
  "Circuit Breaker": "سرکٹ بریکر",
  "A PSX auto-halt triggered when the index moves ±5% to curb volatility.": "ایک PSX آٹو ہالٹ جو اس وقت متحرک ہوتا ہے جب انڈیکس ±5% حرکت کرتا ہے تاکہ اتار چڑھاؤ کو روکا جا سکے۔",
  "Pro Tip": "پرو ٹِپ",
  "Important": "اہم",
  "Real Example": "حقیقی مثال",
  "Note": "نوٹ",
  "read": "پڑھیں",
  "questions": "سوالات",
  "Earn up to 50 XP": "50 XP تک حاصل کریں",
  "Score 2+ to complete this lesson.": "اس سبق کو مکمل کرنے کے لیے 2+ اسکور کریں۔",
  "Hi! I'm here to help you understand": "ہیلو! میں آپ کو سمجھانے کے لیے حاضر ہوں",
  "What would you like to know?": "آپ کیا جاننا چاہیں گے؟"
};
