/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PsxRouteImport } from './routes/psx'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as StockTickerRouteImport } from './routes/stock.$ticker'
import { Route as LearnLessonIdRouteImport } from './routes/learn.lesson.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PsxRoute = PsxRouteImport.update({
  id: '/psx',
  path: '/psx',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const StockTickerRoute = StockTickerRouteImport.update({
  id: '/stock/$ticker',
  path: '/stock/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonIdRoute = LearnLessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => LearnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/finance': typeof FinanceRoute
  '/learn': typeof LearnRouteWithChildren
  '/plans': typeof PlansRoute
  '/portfolio': typeof PortfolioRoute
  '/psx': typeof PsxRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stock/$ticker': typeof StockTickerRoute
  '/learn/': typeof LearnIndexRoute
  '/learn/lesson/$id': typeof LearnLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/finance': typeof FinanceRoute
  '/plans': typeof PlansRoute
  '/portfolio': typeof PortfolioRoute
  '/psx': typeof PsxRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stock/$ticker': typeof StockTickerRoute
  '/learn': typeof LearnIndexRoute
  '/learn/lesson/$id': typeof LearnLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/finance': typeof FinanceRoute
  '/learn': typeof LearnRouteWithChildren
  '/plans': typeof PlansRoute
  '/portfolio': typeof PortfolioRoute
  '/psx': typeof PsxRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stock/$ticker': typeof StockTickerRoute
  '/learn/': typeof LearnIndexRoute
  '/learn/lesson/$id': typeof LearnLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/app'
    | '/auth'
    | '/finance'
    | '/learn'
    | '/plans'
    | '/portfolio'
    | '/psx'
    | '/settings'
    | '/sitemap.xml'
    | '/stock/$ticker'
    | '/learn/'
    | '/learn/lesson/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/app'
    | '/auth'
    | '/finance'
    | '/plans'
    | '/portfolio'
    | '/psx'
    | '/settings'
    | '/sitemap.xml'
    | '/stock/$ticker'
    | '/learn'
    | '/learn/lesson/$id'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/app'
    | '/auth'
    | '/finance'
    | '/learn'
    | '/plans'
    | '/portfolio'
    | '/psx'
    | '/settings'
    | '/sitemap.xml'
    | '/stock/$ticker'
    | '/learn/'
    | '/learn/lesson/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  FinanceRoute: typeof FinanceRoute
  LearnRoute: typeof LearnRouteWithChildren
  PlansRoute: typeof PlansRoute
  PortfolioRoute: typeof PortfolioRoute
  PsxRoute: typeof PsxRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StockTickerRoute: typeof StockTickerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psx': {
      id: '/psx'
      path: '/psx'
      fullPath: '/psx'
      preLoaderRoute: typeof PsxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/stock/$ticker': {
      id: '/stock/$ticker'
      path: '/stock/$ticker'
      fullPath: '/stock/$ticker'
      preLoaderRoute: typeof StockTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/lesson/$id': {
      id: '/learn/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/learn/lesson/$id'
      preLoaderRoute: typeof LearnLessonIdRouteImport
      parentRoute: typeof LearnRoute
    }
  }
}

interface LearnRouteChildren {
  LearnIndexRoute: typeof LearnIndexRoute
  LearnLessonIdRoute: typeof LearnLessonIdRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnIndexRoute: LearnIndexRoute,
  LearnLessonIdRoute: LearnLessonIdRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  FinanceRoute: FinanceRoute,
  LearnRoute: LearnRouteWithChildren,
  PlansRoute: PlansRoute,
  PortfolioRoute: PortfolioRoute,
  PsxRoute: PsxRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StockTickerRoute: StockTickerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
